USE ROLE ACCOUNTADMIN;

-- ==========================================
-- WAREHOUSE
-- ==========================================

CREATE OR REPLACE WAREHOUSE AIRBYTE_WAREHOUSE
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;


-- ==========================================
-- 2. DATABASES AND SCHEMAS
-- ==========================================

CREATE DATABASE IF NOT EXISTS DEALERSHIP_RAW;
CREATE SCHEMA IF NOT EXISTS DEALERSHIP_RAW.MYSQL_LOAD;

CREATE DATABASE IF NOT EXISTS DEALERSHIP_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS DEALERSHIP_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS DEALERSHIP_ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DEALERSHIP_ANALYTICS.MARTS;


-- ==========================================
-- 3. AIRBYTE USER AND ROLE
-- ==========================================

CREATE ROLE IF NOT EXISTS AIRBYTE_ROLE;

CREATE USER IF NOT EXISTS AIRBYTE_USER
  PASSWORD = 'Password123!'
  DEFAULT_ROLE = AIRBYTE_ROLE
  DEFAULT_WAREHOUSE = AIRBYTE_WAREHOUSE;

GRANT ROLE AIRBYTE_ROLE TO USER AIRBYTE_USER;

GRANT USAGE ON WAREHOUSE AIRBYTE_WAREHOUSE TO ROLE AIRBYTE_ROLE;
GRANT USAGE ON DATABASE DEALERSHIP_RAW TO ROLE AIRBYTE_ROLE;
GRANT USAGE ON SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA DEALERSHIP_RAW.MYSQL_LOAD
  TO ROLE AIRBYTE_ROLE;

GRANT MODIFY ON SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE AIRBYTE_ROLE;


-- ==========================================
-- 4. DBT USER AND ROLE
-- ==========================================

CREATE ROLE IF NOT EXISTS DBT_ROLE;

CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = 'Password123!'
  DEFAULT_ROLE = DBT_ROLE
  DEFAULT_WAREHOUSE = AIRBYTE_WAREHOUSE;

GRANT ROLE DBT_ROLE TO USER DBT_USER;

GRANT USAGE ON WAREHOUSE AIRBYTE_WAREHOUSE TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE DEALERSHIP_RAW TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE DBT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEALERSHIP_RAW.MYSQL_LOAD TO ROLE DBT_ROLE;


-- ============================================================
-- 6. DBT BUILD PERMISSIONS ON ANALYTICS LAYERS
-- ============================================================

GRANT USAGE ON DATABASE DEALERSHIP_ANALYTICS TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA DEALERSHIP_ANALYTICS.STAGING      TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DEALERSHIP_ANALYTICS.INTERMEDIATE TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DEALERSHIP_ANALYTICS.MARTS        TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DEALERSHIP_ANALYTICS.STAGING
  TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DEALERSHIP_ANALYTICS.INTERMEDIATE
  TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DEALERSHIP_ANALYTICS.MARTS
  TO ROLE DBT_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEALERSHIP_ANALYTICS.STAGING      TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA DEALERSHIP_ANALYTICS.STAGING      TO ROLE DBT_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEALERSHIP_ANALYTICS.INTERMEDIATE TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA DEALERSHIP_ANALYTICS.INTERMEDIATE TO ROLE DBT_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEALERSHIP_ANALYTICS.MARTS        TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA DEALERSHIP_ANALYTICS.MARTS        TO ROLE DBT_ROLE;
